[package]
name = "isp-docs"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
html2md = "0.2.14"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
select = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.5.1"
slug = "0.1.5"
