name: Deploy Documentation

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install MkDocs and dependencies
      run: |
        pip install mkdocs mkdocs-material

    - name: Copy Raw Files to Docs Directory
      run: |
        mkdir -p docs
        cp raw/*.md docs/

    - name: Generate mkdocs.yml
      run: |
        echo "site_name: ISP Docs" > mkdocs.yml
        echo "theme:\n  name: 'material'" >> mkdocs.yml
        NAV_ENTRIES=$(for file in docs/*.md; do filename=$(basename "$file"); name=$(basename "$filename" .md | tr '-' ' ' | awk '{print toupper(substr($0, 1, 1)) tolower(substr($0, 2))}'); echo "  - \"$name\": \"$filename\""; done)
        echo "nav:" >> mkdocs.yml
        echo "$NAV_ENTRIES" >> mkdocs.yml

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
